name: reuselt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.3
  google_maps_flutter: ^2.2.3
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.0.2
  intl: ^0.18.1
  firebase_messaging: ^14.6.3
  geolocator: ^10.1.0
  latlong2: ^0.9.1
  flutter_map: ^8.0.0
  shimmer: ^3.0.0
  timeago: ^3.7.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.6
  http: ^1.3.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/ilus.png